services:
  mysql:
    image: mysql:8.0
    container_name: conjunction_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conjunction_db
      MYSQL_USER: conjuser
      MYSQL_PASSWORD: conjpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
