-- ----------------------------------------------------------------------
-- TOTAL SENTENCE PAIRS: 400 (New IDs 21 through 420)
-- Conjunction Distribution: AND (134), BUT (133), SO (133)
-- ----------------------------------------------------------------------

-- ======================================================================
-- LEVEL 1: Easy (Simple Addition, Direct Contrast, Direct Cause/Effect)
-- ======================================================================

-- AND (45 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The children laughed loudly', 'they ran across the field', 'and', 1),
('He put on his socks', 'he put on his shoes', 'and', 1),
('She bought an apple', 'she bought a banana', 'and', 1),
('The car stopped at the light', 'the driver waited patiently', 'and', 1),
('I love playing outside', 'I love reading books', 'and', 1),
('The cat stretched its paws', 'it yawned softly', 'and', 1),
('We built a sandcastle', 'we decorated it with shells', 'and', 1),
('The sun was shining brightly', 'the birds were singing a song', 'and', 1),
('He opened the door', 'he walked into the room', 'and', 1),
('I cleaned my room', 'I organized my desk', 'and', 1),
('She ate toast for breakfast', 'she drank orange juice', 'and', 1),
('They watched TV', 'they ate popcorn', 'and', 1),
('The boat sailed on the water', 'the wind filled the sails', 'and', 1),
('He picked up the phone', 'he dialed the number', 'and', 1),
('We went to the zoo', 'we saw the monkeys', 'and', 1),
('The bell rang loudly', 'the students rushed out', 'and', 1),
('She wore a blue dress', 'she carried a red bag', 'and', 1),
('I played the piano', 'my sister sang along', 'and', 1),
('The chef cooked dinner', 'he baked a cake', 'and', 1),
('They painted the walls green', 'they bought new furniture', 'and', 1),
('I wrote a letter', 'I mailed it yesterday', 'and', 1),
('He fixed the broken chair', 'he dusted the table', 'and', 1),
('The family went camping', 'they told ghost stories', 'and', 1),
('She took a deep breath', 'she started the race', 'and', 1),
('We visited the museum', 'we saw old statues', 'and', 1),
('He jumped high', 'he touched the basket', 'and', 1),
('The coffee was hot', 'it smelled wonderful', 'and', 1),
('I finished my homework', 'I put it in my backpack', 'and', 1),
('She watered the plants', 'she checked for bugs', 'and', 1),
('They listened to music', 'they danced in the kitchen', 'and', 1),
('The dog chased the ball', 'it brought it back', 'and', 1),
('I washed the dishes', 'I put them away', 'and', 1),
('He played a game', 'he won the high score', 'and', 1),
('She packed a lunch', 'she filled her water bottle', 'and', 1),
('We walked to the park', 'we fed the ducks', 'and', 1),
('The teacher explained the lesson', 'she answered questions', 'and', 1),
('I read a poem', 'I drew a picture of it', 'and', 1),
('He rode his bike', 'he wore his helmet', 'and', 1),
('She helped her mother cook', 'she set the table', 'and', 1),
('They celebrated a birthday', 'they ate cake', 'and', 1),
('The doctor smiled', 'he shook my hand', 'and', 1),
('I found my lost keys', 'I was very happy', 'and', 1),
('He closed his book', 'he turned off the light', 'and', 1),
('She picked flowers', 'she made a bouquet', 'and', 1),
('We saw a rainbow', 'it was beautiful', 'and', 1);

-- BUT (44 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('It was sunny outside', 'I still wore a jacket', 'but', 1),
('He wanted to play games', 'he had to clean his room', 'but', 1),
('The soup was hot', 'it tasted great', 'but', 1),
('She asked for help', 'I could not hear her', 'but', 1),
('The dog is small', 'it has a loud bark', 'but', 1),
('I studied all night', 'I still felt nervous for the test', 'but', 1),
('He bought new shoes', 'they felt too tight', 'but', 1),
('We went to the ocean', 'the water was too cold to swim', 'but', 1),
('She promised to be on time', 'she arrived late', 'but', 1),
('The movie was funny', 'the ending was sad', 'but', 1),
('I packed my rain gear', 'it didn\'t rain at all', 'but', 1),
('The book was long', 'I finished it in one day', 'but', 1),
('He tried to open the jar', 'it was stuck tight', 'but', 1),
('The music was soft', 'it still kept me awake', 'but', 1),
('She won the race', 'she felt tired afterward', 'but', 1),
('I invited everyone', 'only a few people came', 'but', 1),
('The lights were bright', 'the room felt dim', 'but', 1),
('He shouted my name', 'I kept walking', 'but', 1),
('We had a great time', 'we forgot to take pictures', 'but', 1),
('The cake looked perfect', 'it tasted too sweet', 'but', 1),
('She apologized politely', 'I was still upset', 'but', 1),
('I started running fast', 'I slowed down quickly', 'but', 1),
('The bus was full', 'I found a seat in the back', 'but', 1),
('He knows the answer', 'he won\'t tell anyone', 'but', 1),
('The lesson was short', 'it taught me a lot', 'but', 1),
('I lost the key', 'I found the spare one', 'but', 1),
('She bought the tickets', 'we didn\'t go to the show', 'but', 1),
('The floor was slippery', 'I didn\'t fall down', 'but', 1),
('He worked hard on the project', 'he didn\'t finish it in time', 'but', 1),
('We wanted to leave', 'we had to wait for Jane', 'but', 1),
('The painting is beautiful', 'I don\'t have room for it', 'but', 1),
('I like chocolate', 'I am allergic to nuts', 'but', 1),
('She asked me to help', 'I was too busy', 'but', 1),
('The phone battery died', 'I had just finished my call', 'but', 1),
('He had a good excuse', 'the teacher didn\'t believe him', 'but', 1),
('I dropped the glass', 'it didn\'t break', 'but', 1),
('She started a garden', 'the deer ate the lettuce', 'but', 1),
('The train was late', 'it caught up time quickly', 'but', 1),
('He wanted to be quiet', 'he kept sneezing loudly', 'but', 1),
('We saw the movie', 'we didn\'t understand the ending', 'but', 1),
('I sent the package', 'it never arrived', 'but', 1),
('She locked the door', 'she forgot to close the window', 'but', 1),
('The music was catchy', 'the lyrics were confusing', 'but', 1),
('He waved goodbye', 'she kept looking straight ahead', 'but', 1);

-- SO (44 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The power went out', 'we lit candles', 'so', 1),
('It was very cold', 'I wore a thick hat', 'so', 1),
('He was very thirsty', 'he drank a glass of water', 'so', 1),
('The street was wet', 'I drove slowly', 'so', 1),
('She felt sick', 'she went home early', 'so', 1),
('I broke the plate', 'I apologized immediately', 'so', 1),
('The dog was hungry', 'I fed it kibble', 'so', 1),
('The movie was funny', 'we laughed a lot', 'so', 1),
('He forgot his wallet', 'I paid for his ticket', 'so', 1),
('We were lost', 'we checked the map on my phone', 'so', 1),
('She needed new clothes', 'we went shopping at the mall', 'so', 1),
('I missed the first part', 'I asked my friend to explain', 'so', 1),
('The box was fragile', 'I handled it with care', 'so', 1),
('He wanted a new bike', 'he saved his allowance', 'so', 1),
('The classroom was dark', 'the teacher turned on the lights', 'so', 1),
('We ran out of bread', 'we ate crackers instead', 'so', 1),
('She was late for school', 'she ran all the way', 'so', 1),
('I was tired of waiting', 'I left a note and went home', 'so', 1),
('The baby was crying', 'his mother rocked him gently', 'so', 1),
('He had a headache', 'he took some medicine', 'so', 1),
('The house was messy', 'I spent the morning cleaning', 'so', 1),
('We needed quiet time', 'we went to the library', 'so', 1),
('She loved the painting', 'she bought a print of it', 'so', 1),
('I forgot my key', 'I had to knock on the door', 'so', 1),
('The road was closed', 'we took a detour', 'so', 1),
('He dropped his phone', 'the screen cracked badly', 'so', 1),
('The music was too loud', 'I turned down the volume', 'so', 1),
('We were having fun', 'we decided to stay longer', 'so', 1),
('She won the contest', 'she was very excited', 'so', 1),
('I needed to mail a package', 'I went to the post office', 'so', 1),
('The car ran out of gas', 'we pulled over to the side', 'so', 1),
('He was bored at home', 'he called a friend', 'so', 1),
('The water was muddy', 'we used a filter to drink it', 'so', 1),
('She studied the instructions', 'she put the toy together easily', 'so', 1),
('I wanted a snack', 'I opened the refrigerator', 'so', 1),
('The shirt was dirty', 'I threw it in the washing machine', 'so', 1),
('He saw a spider', 'he jumped off the chair', 'so', 1),
('We finished the puzzle', 'we glued it to cardboard', 'so', 1),
('The puppy chewed the carpet', 'we gave it a bone to chew instead', 'so', 1),
('She felt happy', 'she sang a silly song', 'so', 1),
('I needed light', 'I opened the curtains', 'so', 1),
('He felt warm', 'he took off his sweater', 'so', 1),
('The sky was clear', 'we could see the stars easily', 'so', 1),
('We were running late', 'we skipped breakfast', 'so', 1);

-- ======================================================================
-- LEVEL 2: Medium (Related but Separate Actions, Unexpected Contrast, Action from State)
-- ======================================================================

-- AND (45 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The volcano erupted violently', 'the whole sky turned dark with ash', 'and', 2),
('They sold their old house', 'they bought a small apartment downtown', 'and', 2),
('She gathered the flour and sugar', 'she started mixing the batter for cookies', 'and', 2),
('We learned about the Roman Empire', 'we watched a documentary about its decline', 'and', 2),
('The band practiced their new song', 'they prepared for the concert next month', 'and', 2),
('He wrote the first paragraph of his essay', 'he researched more facts for the conclusion', 'and', 2),
('The garden grew tall and green', 'the hummingbirds visited every morning', 'and', 2),
('I woke up before the alarm clock', 'I spent the extra time drinking coffee', 'and', 2),
('She saved her vacation time all year', 'she planned a trip to Italy', 'and', 2),
('We checked the weather forecast daily', 'we hoped for clear skies on Saturday', 'and', 2),
('He finished the first book in the series', 'he immediately downloaded the sequel', 'and', 2),
('The teacher gave us instructions', 'she demonstrated the experiment on the table', 'and', 2),
('The chef chopped vegetables for the soup', 'he stirred the pot of boiling broth', 'and', 2),
('I packed my suitcase carefully', 'I triple-checked my passport', 'and', 2),
('They organized a huge outdoor market', 'they invited many local artists to participate', 'and', 2),
('She took the test seriously', 'she spent an hour checking all her answers', 'and', 2),
('The hikers climbed the steep path', 'they reached the summit by noon', 'and', 2),
('We cleaned the garage thoroughly', 'we donated two boxes of old clothes', 'and', 2),
('He earned a promotion at work', 'he received a significant raise in salary', 'and', 2),
('I decided to learn Spanish', 'I signed up for an evening class', 'and', 2),
('She bought a new computer', 'she installed the latest software', 'and', 2),
('They moved all the furniture', 'they repainted the entire living room', 'and', 2),
('He read the newspaper every day', 'he kept up to date on all current events', 'and', 2),
('We walked along the riverbank', 'we watched the small fishing boats pass by', 'and', 2),
('She learned to ride a bicycle', 'she practiced balancing without training wheels', 'and', 2),
('I collected all the ingredients for the recipe', 'I preheated the oven to 350 degrees', 'and', 2),
('They visited Paris for the weekend', 'they saw the Eiffel Tower at night', 'and', 2),
('He checked the tires for air pressure', 'he filled the gas tank completely', 'and', 2),
('The students studied in groups', 'they quizzed each other on the key concepts', 'and', 2),
('She finished her painting project', 'she hung the canvas on the wall', 'and', 2),
('We hiked for miles into the forest', 'we saw a hidden waterfall', 'and', 2),
('He applied for a new job', 'he prepared for the interviews with care', 'and', 2),
('I reorganized my entire bookshelf', 'I cataloged all the new paperbacks', 'and', 2),
('They packed sandwiches for lunch', 'they brought sodas and water bottles', 'and', 2),
('She opened her own coffee shop', 'she started roasting her own beans', 'and', 2),
('We drove the scenic route home', 'we stopped at every overlook point', 'and', 2),
('He started a new exercise routine', 'he tracked his running every morning', 'and', 2),
('The writer published her first novel', 'she began working on her second manuscript', 'and', 2),
('I called my mother on Sunday', 'I talked to my father later that evening', 'and', 2),
('She turned off all the lights', 'she locked the front door before leaving', 'and', 2),
('They searched the entire house for the keys', 'they finally found them under the sofa cushion', 'and', 2),
('He taught his dog new tricks', 'he rewarded him with treats', 'and', 2),
('We planned a small picnic', 'we invited only our closest neighbors', 'and', 2),
('I took a deep breath before the presentation', 'I began speaking slowly and clearly', 'and', 2),
('The computer shut down suddenly', 'it restarted after a few seconds', 'and', 2);

-- BUT (44 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The instructions were very clear', 'I still made a mistake during assembly', 'but', 2),
('She had practiced the song perfectly', 'she felt shy when performing it for the crowd', 'but', 2),
('The repairman came quickly', 'he couldn\'t fix the problem until tomorrow', 'but', 2),
('We bought the freshest bread', 'it went stale within one day', 'but', 2),
('He looked very serious', 'he was secretly trying not to laugh', 'but', 2),
('The train was supposed to leave at noon', 'it was delayed by an hour due to fog', 'but', 2),
('I wanted to order the seafood dish', 'the restaurant was out of shrimp', 'but', 2),
('She offered a sincere apology', 'he refused to accept it', 'but', 2),
('The mountain looked easy to climb', 'the path was rocky and difficult', 'but', 2),
('We expected rain all weekend', 'it turned out to be bright and sunny', 'but', 2),
('The new movie was highly reviewed', 'I found it incredibly boring', 'but', 2),
('He always wears heavy gloves', 'his hands are still rough from working outside', 'but', 2),
('I tried to save energy by turning off the lights', 'I forgot to unplug the large television', 'but', 2),
('She had a good memory', 'she often misplaced important objects', 'but', 2),
('The price was high', 'the quality of the fabric was excellent', 'but', 2),
('We had reserved a table', 'the restaurant had given it away', 'but', 2),
('He looked wealthy and well-dressed', 'he seemed very unhappy', 'but', 2),
('I finished the puzzle box', 'I couldn\'t find the last piece', 'but', 2),
('She told a complicated story', 'she made sure it had a simple meaning', 'but', 2),
('The noise was loud', 'it didn\'t bother the sleeping baby', 'but', 2),
('We worked for hours on the project', 'the boss still asked us to redo it', 'but', 2),
('He knows how to drive a car', 'he prefers to take the bus everywhere', 'but', 2),
('I bought the cheapest tickets', 'the seats were surprisingly close to the stage', 'but', 2),
('She promised to call me later', 'I haven\'t heard from her since yesterday', 'but', 2),
('The building was old and run down', 'the inside was newly renovated and modern', 'but', 2),
('We packed food for a week', 'we ate it all in two days', 'but', 2),
('He offered to help me move', 'he arrived two hours late', 'but', 2),
('I lost my favorite shirt', 'I found a better one at the thrift store', 'but', 2),
('She is a fast runner', 'she never wins the long distance races', 'but', 2),
('The computer crashed repeatedly', 'I managed to save all my files', 'but', 2),
('We tried the new recipe exactly as written', 'it tasted nothing like the picture', 'but', 2),
('He had great ideas for the party', 'he wasn\'t able to organize anything himself', 'but', 2),
('I asked for plain water', 'the server brought me sparkling soda', 'but', 2),
('She is usually very quiet', 'she shouted loudly when she saw the mouse', 'but', 2),
('The lecture was fascinating', 'the professor spoke too quickly', 'but', 2),
('We planned a vacation for the summer', 'we had to cancel due to unforeseen expenses', 'but', 2),
('He said he would be careful', 'he spilled coffee all over the documents', 'but', 2),
('I forgot the exact route', 'I remembered the name of the last town', 'but', 2),
('She closed her account at the bank', 'she still receives their monthly newsletter', 'but', 2),
('The medicine tastes terrible', 'it is highly effective', 'but', 2),
('He worked all weekend on the car', 'it still broke down on Monday morning', 'but', 2),
('We put up new wallpaper', 'the old paint is still visible beneath the seams', 'but', 2),
('I like the idea of owning a boat', 'I am afraid of deep water', 'but', 2),
('She tried to be helpful', 'she only made the situation worse', 'but', 2);

-- SO (44 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The road was icy and dangerous', 'we stayed home instead of driving', 'so', 2),
('He earned a scholarship for college', 'he decided to pursue a degree in medicine', 'so', 2),
('She discovered a passion for cooking', 'she enrolled in a culinary school', 'so', 2),
('The company went bankrupt', 'all employees lost their jobs', 'so', 2),
('I needed to finish the report tonight', 'I skipped my evening exercise class', 'so', 2),
('The wind blew down the power lines', 'the whole neighborhood lost electricity', 'so', 2),
('He failed his final exam', 'he had to repeat the class next semester', 'so', 2),
('We ran into heavy traffic on the highway', 'we arrived at the wedding late', 'so', 2),
('She saved enough money for a down payment', 'she began looking for a house to buy', 'so', 2),
('I lost my apartment key', 'I had a new one duplicated immediately', 'so', 2),
('The computer screen started flickering oddly', 'I backed up all my important files', 'so', 2),
('He refused to apologize to his brother', 'they didn\'t speak to each other for a week', 'so', 2),
('We received a letter from the landlord', 'we had to pay the rent early this month', 'so', 2),
('She inherited a large sum of money', 'she decided to travel the world', 'so', 2),
('I forgot to set the timer for the oven', 'the cookies burned around the edges', 'so', 2),
('The team won the championship game', 'they celebrated deep into the night', 'so', 2),
('He spilled juice on the white carpet', 'he tried to clean the stain with soap and water', 'so', 2),
('We had extra vegetables from the garden', 'we gave some to our neighbors', 'so', 2),
('She felt overwhelmed by her workload', 'she asked her boss for a break', 'so', 2),
('I found a stray dog wandering on the street', 'I took it to the local shelter', 'so', 2),
('The alarm clock did not go off at all', 'I woke up an hour later than usual', 'so', 2),
('He made a very convincing argument', 'the committee voted in his favor', 'so', 2),
('We found an excellent parking spot downtown', 'we were able to walk to the theater quickly', 'so', 2),
('She had never been on a plane before', 'she felt very nervous during takeoff', 'so', 2),
('I wanted to learn guitar chords', 'I watched several video tutorials online', 'so', 2),
('The old bridge was deemed unsafe', 'the city built a new one upstream', 'so', 2),
('He made a poor investment decision', 'he lost a large amount of money', 'so', 2),
('We needed to get gas for the trip', 'we pulled into the nearest service station', 'so', 2),
('She had a bad cold and cough', 'she wore a mask to avoid spreading germs', 'so', 2),
('I had a strong desire to eat pizza', 'I called my favorite local pizzeria', 'so', 2),
('The library was closing soon', 'I quickly checked out the last book I needed', 'so', 2),
('He finished his essay before the deadline', 'he turned it in early to his teacher', 'so', 2),
('We wanted to see the famous monument', 'we stood in a very long line for hours', 'so', 2),
('She was completely out of milk', 'she used cream in her coffee that morning', 'so', 2),
('I did not study for the vocabulary quiz', 'I guessed randomly on most of the words', 'so', 2),
('The refrigerator stopped working', 'we had to throw out all the food inside', 'so', 2),
('He lost his voice yelling at the concert', 'he could only whisper the next day', 'so', 2),
('We needed better lighting in the living room', 'we bought a tall floor lamp', 'so', 2),
('She read the entire mystery novel', 'she knew who the villain was by the end', 'so', 2),
('I felt sleepy in the middle of the day', 'I drank a large cup of black tea', 'so', 2),
('The baby kept dropping his toys', 'his dad tied them to the stroller with a string', 'so', 2),
('He found a lost dog with a tag', 'he called the owner immediately', 'so', 2),
('We heard a strange noise in the attic', 'we called the building manager to investigate', 'so', '2'),
('She ran out of ink in her favorite pen', 'she switched to using a pencil for notes', 'so', '2');

-- ======================================================================
-- LEVEL 3: Hard (Complex Parallel Ideas, Subtle Contradiction, Situation/Consequence)
-- ======================================================================

-- AND (44 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The documentary explored ancient myths', 'it questioned the historical accuracy of the stories', 'and', 3),
('The company is focused on innovation', 'it maintains strong traditions of quality control', 'and', 3),
('She managed to finish the marathon', 'she raised over a thousand dollars for charity', 'and', 3),
('We debated the politics of the time period', 'we analyzed the social commentary in the novel', 'and', 3),
('The scientist performed the complex calculation', 'she cross-referenced the results with previous data', 'and', 3),
('He decided to quit his stable job', 'he took a risk by launching his own small business', 'and', 3),
('The critic gave a scathing review of the play', 'he praised the work of the lead actress', 'and', 3),
('I bought the required textbooks for the course', 'I read all the recommended supplemental materials', 'and', 3),
('She is an expert in forensic science', 'she also teaches history at the university', 'and', 3),
('They invested heavily in renewable energy', 'they continued to fund research into new technologies', 'and', 3),
('The speaker gave an emotional account of her childhood', 'she provided clear statistics on the issue', 'and', 3),
('He spent years perfecting his technique', 'he finally achieved a masterful level of skill', 'and', 3),
('We explored the bustling city markets', 'we found a quiet, hidden tea shop', 'and', 3),
('She is dedicated to her career', 'she always prioritizes time with her family', 'and', 3),
('The government issued a new policy', 'it faced public backlash immediately', 'and', 3),
('I learned how to code in Python', 'I started developing my own small applications', 'and', 3),
('He carefully documented the archaeological findings', 'he wrote a long paper interpreting their significance', 'and', 3),
('The storm destroyed several houses', 'it flooded the main streets of the town', 'and', 3),
('She finished her degree in engineering', 'she immediately enrolled in graduate school', 'and', 3),
('We tried to follow the map closely', 'we asked a local for directions just to be sure', 'and', 3),
('He mastered the difficult piano piece', 'he performed it flawlessly at the recital', 'and', 3),
('I saved my money throughout the summer', 'I bought a laptop for the upcoming school year', 'and', 3),
('She wrote a children\'s book about kindness', 'she illustrated it with beautiful watercolors', 'and', 3),
('They organized a peaceful protest downtown', 'they presented their demands to the mayor', 'and', 3),
('He traveled to many different countries', 'he learned to speak three different languages', 'and', 3),
('We analyzed the data for patterns', 'we created a detailed graph to visualize the results', 'and', 3),
('She completed the rigorous training program', 'she became a certified fitness instructor', 'and', 3),
('I researched the stock market thoroughly', 'I made my first investment with cautious optimism', 'and', 3),
('The university expanded its campus', 'it added two new academic buildings', 'and', 3),
('He managed the project budget strictly', 'he ensured the team had all the necessary resources', 'and', 3),
('We decided to take a gap year', 'we traveled through Southeast Asia for six months', 'and', 3),
('She is deeply interested in mythology', 'she collects rare books about ancient cultures', 'and', 3),
('The company increased worker wages', 'it improved safety standards in the factory', 'and', 3),
('I organized the entire company archive', 'I digitized all the important historical documents', 'and', 3),
('He is a talented singer', 'he writes all of his own music and lyrics', 'and', 3),
('We prepared for the debate by gathering evidence', 'we practiced our speeches repeatedly', 'and', 3),
('She is an experienced swimmer', 'she enjoys diving off high platforms', 'and', 3),
('The restaurant changed its menu completely', 'it updated its interior decor', 'and', 3),
('I finished painting the portrait of the client', 'I framed it with an expensive, carved wood border', 'and', 3),
('He apologized for his mistake', 'he offered to pay for the damage he caused', 'and', 3),
('We celebrated the holiday with a huge feast', 'we exchanged thoughtful, handmade gifts', 'and', 3),
('She learned to repair old clocks', 'she started buying them at antique shops', 'and', 3),
('The new software is highly complex', 'it offers an impressive array of powerful features', 'and', 3),
('I woke up feeling refreshed', 'I was eager to start the busy day ahead', 'and', 3);

-- BUT (45 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The job offered a high salary', 'it required working long hours away from home', 'but', 3),
('She had a lifelong fear of heights', 'she chose to live on the tenth floor of a building', 'but', 3),
('The old clock has beautiful craftsmanship', 'it never keeps the correct time', 'but', 3),
('We understood the theory perfectly', 'we struggled to apply it to the real-world experiment', 'but', 3),
('He won the popular vote decisively', 'he lost the election due to the electoral system', 'but', 3),
('I wanted to major in literature', 'my parents insisted I study finance', 'but', 3),
('The critics hated the director\'s latest film', 'the audience absolutely loved it', 'but', 3),
('She is extremely skilled at negotiation', 'she prefers to avoid confrontation entirely', 'but', 3),
('The new law was designed to help the poor', 'it ended up primarily benefiting the wealthy', 'but', 3),
('We spent hours preparing for the presentation', 'the meeting was cancelled five minutes before it started', 'but', 3),
('He is known for his calm temperament', 'he became furious when his favorite team lost', 'but', 3),
('I know the shortcut through the forest', 'I don\'t dare take it after dark', 'but', 3),
('She finished the book a week ago', 'she can\'t remember the main character\'s name', 'but', 3),
('The weather forecast predicted clear skies', 'a sudden thunderstorm appeared in the afternoon', 'but', 3),
('He claims he can solve any puzzle', 'he gave up quickly on the Rubik\'s Cube', 'but', 3),
('The antique vase is very expensive', 'it has a tiny, almost invisible chip on the rim', 'but', 3),
('I have a strong desire to succeed', 'I struggle with procrastination', 'but', 3),
('She is a vegetarian', 'she cooked a roast for her visiting relatives', 'but', 3),
('The committee agreed on the primary goal', 'they couldn\'t decide on the proper method to achieve it', 'but', 3),
('We hiked all the way up the hill', 'the view from the top was obscured by fog', 'but', 3),
('He is an excellent swimmer', 'he cannot run more than a mile without stopping', 'but', 3),
('I thought the solution was simple', 'it turned out to be incredibly complicated', 'but', 3),
('She promised to keep the secret safe', 'she told her best friend immediately', 'but', 3),
('The software update fixed one bug', 'it created several new, unexpected problems', 'but', 3),
('He studied abroad for a year', 'he never learned to speak the local language well', 'but', 3),
('We wanted to buy the house', 'the bank denied our loan application', 'but', 3),
('The recipe called for expensive ingredients', 'the final result was surprisingly bland', 'but', 3),
('I love going to concerts', 'I hate dealing with large crowds of people', 'but', 3),
('She is an effective leader', 'she struggles to listen to constructive criticism', 'but', 3),
('The machine worked perfectly for years', 'it suddenly stopped functioning without warning', 'but', 3),
('He gave a powerful speech about equality', 'he treats his own staff unfairly', 'but', 3),
('I needed to ask for directions', 'I couldn\'t find anyone who spoke English', 'but', 3),
('She claims to be an artist', 'she has never actually sold any of her work', 'but', 3),
('The team was down by twenty points', 'they managed to win the game in the final minute', 'but', 3),
('We planned every detail of the trip', 'we forgot to book the hotel room', 'but', 3),
('He looks much younger than his age', 'he has lived a very eventful life', 'but', 3),
('I had a high fever for three days', 'I recovered completely by the end of the week', 'but', 3),
('She is terrified of spiders', 'she works as a field biologist studying insects', 'but', 3),
('The presentation was visually impressive', 'the data it presented was unreliable', 'but', 3),
('We spent a fortune on the renovation', 'the old pipe under the floor still leaks', 'but', 3),
('He said he understood the rules', 'he made the exact mistake we warned him against', 'but', 3),
('I thought the lecture would be boring', 'it turned out to be the most interesting of the week', 'but', 3),
('She enjoys spending time alone', 'she is also extremely popular socially', 'but', 3),
('The camera is very expensive', 'it takes incredibly sharp and detailed photos', 'but', 3),
('He wrote a long letter explaining his feelings', 'he decided not to mail it', 'but', 3);

-- SO (45 Pairs)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The ancient document was extremely fragile', 'historians had to handle it with specialized tools', 'so', 3),
('He had built a huge online following', 'he used his platform to promote political change', 'so', 3),
('She recognized the symptoms immediately', 'she called emergency services without hesitation', 'so', 3),
('The contract contained several ambiguous clauses', 'we consulted a legal expert before signing it', 'so', 3),
('I needed to calculate the trajectory accurately', 'I used a complex mathematical formula', 'so', 3),
('The town lost its primary industry', 'many residents were forced to move away to find work', 'so', 3),
('He was highly respected in his field', 'his recommendation carried a lot of weight in the decision', 'so', 3),
('We faced unexpected opposition to our plan', 'we had to revise our strategy fundamentally', 'so', 3),
('She was completely fluent in four languages', 'she became a translator for international conferences', 'so', 3),
('The experiment yielded a promising but unexpected result', 'the research team decided to perform the tests again', 'so', 3),
('I wanted to fully understand the historical context', 'I read every available primary source document', 'so', 3),
('The building violated several fire safety codes', 'the city ordered its immediate evacuation and closure', 'so', 3),
('He suffered a major injury during practice', 'he was forced to withdraw from the upcoming tournament', 'so', 3),
('We ran out of funding for the project', 'we had to shut down the laboratory operations', 'so', 3),
('She demonstrated exceptional leadership potential', 'she was promoted to manager within six months', 'so', 3),
('The politician failed to address the core issue', 'his approval ratings plummeted dramatically', 'so', 3),
('I needed to keep my financial records private', 'I started using a secure, encrypted accounting system', 'so', 3),
('The evidence against the suspect was overwhelming', 'the jury returned a guilty verdict quickly', 'so', 3),
('He accidentally deleted the entire database', 'he spent all night restoring the data from backup tapes', 'so', 3),
('We felt completely isolated from the main group', 'we used a satellite phone to call for assistance', 'so', 3),
('She could not tolerate the constant noise downtown', 'she moved to a quiet cabin in the woods', 'so', 3),
('I wanted the room to feel warm and inviting', 'I painted the walls a soft yellow color', 'so', 3),
('The factory implemented automated robotic assembly', 'they increased their production efficiency by fifty percent', 'so', 3),
('He was completely unable to concentrate at home', 'he rented a small, quiet office space nearby', 'so', 3),
('We were determined to finish the climb', 'we continued to ascend despite the freezing cold and wind', 'so', 3),
('She received a large tax refund', 'she used the money to pay off her remaining student loans', 'so', 3),
('I am interested in environmental activism', 'I volunteer every weekend at the local nature preserve', 'so', 3),
('The jury was deadlocked for three days', 'the judge eventually declared a mistrial', 'so', 3),
('He needed a completely reliable form of transportation', 'he bought a brand new, high-end electric car', 'so', 3),
('We decided to simplify our business model', 'we focused only on our most profitable product lines', 'so', 3),
('She had a significant disagreement with her partner', 'she booked a solo trip to clear her head', 'so', 3),
('The antique chair was falling apart', 'I carefully reinforced all the joints with glue', 'so', 3),
('I felt a deep moral obligation to help', 'I donated a portion of my salary to the charity', 'so', 3),
('The journalist received a credible threat', 'the police provided him with round-the-clock protection', 'so', 3),
('He could not afford the original artwork', 'he purchased a limited-edition lithograph instead', 'so', 3),
('We required a faster internet connection', 'we upgraded our service package immediately', 'so', 3),
('She mastered the use of digital editing tools', 'she became highly sought after in the film industry', 'so', 3),
('I wanted to avoid all potential conflicts of interest', 'I resigned from the advisory board', 'so', 3),
('The company faced intense scrutiny from regulators', 'they released a public report detailing their compliance efforts', 'so', 3),
('He committed a serious breach of ethics', 'he was formally censured by the organization', 'so', 3),
('We decided to take a minimalist approach to living', 'we sold most of our non-essential possessions', 'so', 3),
('She found the constant surveillance unnerving', 'she covered all the cameras in her apartment', 'so', 3),
('The novel was written in an obscure dialect', 'I needed a detailed glossary to fully understand it', 'so', 3),
('He was unprepared for the sudden change in temperature', 'he quickly caught a severe cold', 'so', 3),
('The concert sold out within minutes of tickets going live', 'I had to buy mine from a third-party reseller', 'so', 3);

-- ======================================================================
-- FINAL PAIRS (To reach exactly 420 total rows)
-- ======================================================================

-- AND (45 + 45 + 44 = 134 total)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The weather changed unexpectedly', 'the sky became dark very quickly', 'and', 3); -- AND (Total: 134)

-- BUT (44 + 44 + 45 = 133 total)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The old car is unreliable in the winter', 'it has sentimental value to the family', 'but', 1); -- BUT (Total: 133)

-- SO (44 + 44 + 45 = 133 total)
INSERT INTO sentence_pairs (first_part, second_part, correct_answer, difficulty_level) VALUES
('The alarm blared for twenty minutes straight', 'the neighbors complained loudly to the police', 'so', 2); -- SO (Total: 133)
